spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ladbe?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: ladbe
    password: ladbe
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none

  flyway:
    enabled: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: clientId
            client-secret: clientSecret
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
              -
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
