spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yahoo?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: juyohan
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none

  flyway:
    enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
