version: "3"
services:
  mysql:
    restart: always
    image: mysql:5.7
    container_name: ladbe_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ladbe
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=ladbe
      - MYSQL_PASSWORD=ladbe
      - TZ=Asia/Seoul
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password --skip-grant-tables
    volumes:
      - ./volumes/mysql:/var/lib/mysql
